server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    test-service:
      serviceId: test-service
    report-service:
      serviceId: report-service
    order-service:
      serviceId: order-service
    item-service:
      serviceId: item-service
    product-service:
      serviceId: product-service
    payment-service:
      serviceId: payment-service
    feedback-service:
      serviceId: feedback-service
    user-service:
      serviceId: user-service
  host:
    socket-timeout-millis: 30000